CREATE TABLE USERS_DATA
  (
  ID INTEGER PRIMARY KEY,
  HASHPWD VARCHAR2(255) NOT NULL,  
  SALT VARCHAR2(255) NOT NULL,  
  LOGIN VARCHAR2(255) UNIQUE NOT NULL
  );
/
CREATE SEQUENCE USERS_DATA_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 10;
/
CREATE TABLE ROLES_DATA
  (
  ID INTEGER PRIMARY KEY,
  ROLENAME VARCHAR2(255) UNIQUE
  );
/
CREATE SEQUENCE ROLES_DATA_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 10;
/
CREATE TABLE USERS_ROLES
  (
  UserID INTEGER NOT NULL,
  RoleID INTEGER NOT NULL,
  FOREIGN KEY (UserID) REFERENCES USERS_DATA(ID),
  FOREIGN KEY (RoleID) REFERENCES ROLES_DATA(ID),
  PRIMARY KEY (UserID, RoleID)
  );
/
CREATE TABLE USER_AUTHORIZATION
  (
  UserName VARCHAR(255) NOT NULL,
  AuthTime DATE
  );
/
CREATE TABLE ACTION_LOG
  (
  ACTION VARCHAR(255) NOT NULL,
  TARGET VARCHAR(255) NOT NULL,
  ACTIONUSER VARCHAR2(255),
  ActionDesc VARCHAR2(255),
  ActionDate DATE
  );
