DECLARE
  Retval INT;
BEGIN
USER_MANAGEMENT.ADD_ROLE('Bitter');
USER_MANAGEMENT.ADD_ROLE('SWEET');
USER_MANAGEMENT.ALTER_ROLE('SWEET','sweet',Retval);

USER_MANAGEMENT.ADD_USER('Asder','A','S');
USER_MANAGEMENT.ADD_USER('Sag','H','Q');
USER_MANAGEMENT.ALTER_USER_PWD_SALT('Asder','A','B','V',Retval);

USER_MANAGEMENT.AUTH_USER('Asder','B',Retval);

USER_MANAGEMENT.SET_ROLE_TO_USER('Asder','sweet',Retval);
USER_MANAGEMENT.CHECK_USER_ROLE('Asder','sweet',RetVal);
dbms_output.put_line('SCHEK_USER_ROLE '||RetVal);

USER_MANAGEMENT.DROP_USER('Sag','H',Retval);
USER_MANAGEMENT.DROP_ROLE('Bitter',Retval);

USER_MANAGEMENT.REMOVE_ROLE_FROM_USER('Asder','sweet',RetVal);


 END;